platform :ios, '8.0'
use_frameworks!

target 'BeautifulPhotos' do
  pod 'Alamofire', '1.3.1'
  pod 'SwiftyJSON', '2.2.1'
  pod 'SDWebImage', '3.7.3'
  pod 'MJRefresh', '2.4.8'
  pod 'KxMenu', '~> 1'
end

target 'BeautifulPhotosTests' do

end

